import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
// import styles from '../styles/Home.module.css'
import styles from './projects.module.css'

const inter = Inter({ subsets: ["latin"] });

export default function Home({ blogs, clogs }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.mainmain}>
          <div>
          <img
        alt="pic"
        src="https://avatars.githubusercontent.com/u/106387298?s=400&u=805acac7f1fcd2071bee13ca5eeb423a0dccc416&v=4"
        width={100}
        height={100}
        style={{borderRadius:'50%'}}/>
        <h3>Kausik Bhaumik</h3>
            <p>@{blogs.login}</p>
            <h5>Full-stack Developer | FOSS | JavaScript | Typescript | NodeJS | </h5>
            <h5>Deno | ReactJS | HTML | CSS | Chakra-UI | MUI</h5>
            <button>Resume</button>
            <button>Follow</button>
          </div>
          <div className={styles.mainDiv1}>
            {clogs.map((blog) => (
              <div
                style={{
                  border: "1px solid black",
                  borderRadius: "10px",
                  top: "10px",
                }}
              >
                <h2>{blog.name}</h2>
                <h4>{blog.full_name}</h4>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let res = await fetch("https://api.github.com/users/Loki343");
  let res1 = await fetch(
    "https://api.github.com/search/repositories?q=user:Loki343+fork:true&sort=updated&per_page=10&type=Repositories"
  );
  let data = await res.json();
  let data1 = await res1.json();

  return {
    props: {
      blogs: data,
      clogs: data1.items,
    },
  };
}
